service: crawler
app: widespachante-crawler
#tenant: your-tenant-name


plugins:
  - serverless-offline
  
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  Crawl:
    handler: api/crawler.crawl
    events:
      - http: 
          path: busca
          method: get
  Hello:
    handler: api/crawler.hello
    events:
      - http: 
          path: hello
          method: get